name: paystack_africa
description: >
  Flutter helper to create Paystack payment sessions, open an in-app WebView checkout,
  and return success/failure results with typed responses.
version: 2.0.0

repository: https://github.com/goutam2597/paystack_pay.git
issue_tracker: https://github.com/goutam2597/paystack_pay.git
topics:
  - payments
  - checkout
  - paystack
  - nigeria

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.13.0
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  # declare assets here if needed
